upgrade: true
install: never
format: group
reject:
  # ESM modules
  - execa
  # Nx Managed
  - jest
  - '@types/jest'
  - jest-environment-jsdom
  - ts-jest
  - tslib
  - typescript
  - dotenv
  - '@nx/*'
  - '@swc*'
