service: <%= name %>

configValidationMode: error # remove in serverless v3
variablesResolutionMode: 20210326 # remove in serverless v3

plugins:
  - '<%= plugin %>'
  - serverless-offline

package:
  individually: true

custom:
  stage: ${opt:stage, 'dev'}
  serverless-offline:
    httpPort: <%= port %>
    lambdaPort: <%= port - 1000 %>
    noPrependStageInUrl: true
<% if (plugin == 'serverless-bundle') {
%>  bundle:
    linting: false
    tsConfig: 'tsconfig.app.json'<% } %>

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.stage}
  endpointType: regional
  timeout: 20
  lambdaHashingVersion: 20201221 # removes deprecation warning (remove in serverless v3)
  apiGateway:
    shouldStartNameWithService: true # removes deprecation warning (remove in serverless v3)
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: '${file(./src/environments/config.${self:custom.stage}.json):is_production}'

functions:
  foo:
    handler: src/handlers/foo.handler
    events:
      - http:
          method: GET
          path: /foo
