service: <%= name %>

plugins:
  - '<%= plugin %>'
  - serverless-offline

package:
  individually: true

custom:
  stage: ${opt:stage, env:STAGE, 'dev'}
  serverless-offline:
    httpPort: <%= port %>
    lambdaPort: <%= port - 1000 %>
    noPrependStageInUrl: true
<% if (plugin == 'serverless-esbuild') {
%>  esbuild:
    tsconfig: 'tsconfig.app.json'<% } %>

params:
  prod:
    production: true
  default:
    production: false

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${self:custom.stage}
  endpointType: regional
  timeout: 20
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: ${param:production}
    NODE_OPTIONS: --enable-source-maps

functions:
  - ${file(./src/handlers/foo/sls.yml):functions}
