name: Release
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          affected: true
      - name: Start Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
      - name: Publish
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npx nx affected -t publish --parallel 3
        env:
          NPM_PACKAGE_VERSION: ${{ steps.semantic.outputs.new_release_version }}
      - name: Finish Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: cycjimmy/semantic-release-action@v4
