name: Release
on:
  push:
    branches:
      - master
      - 'alpha/*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            tools/src/**/*.js
          key: dependencies-${{ runner.os }}-${{ hashFiles('yarn.lock', 'tools/src/**/*.ts') }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Start Release
        id: semantic
        run: npx semantic-release --dry-run
      - name: Build
        run: yarn nx affected:build --parallel --base ${{ steps.semantic.outputs.last-head || 'HEAD' }} --with-deps
      - name: Publish
        run: yarn nx affected:publish --parallel --base ${{ steps.semantic.outputs.last-head || 'HEAD' }} --with-deps --pkgVersion ${{ steps.semantic.outputs.next-version }}
      - name: Finish Release
        run: npx semantic-release
