name: Release
on:
  push:
    branches:
      - master
      - 'alpha/*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          affected: true
      - name: Start Release
        id: semantic
        run: npx semantic-release --dry-run
      - name: Publish
        run: yarn nx affected --target publish --parallel 3
        env:
          NPM_PACKAGE_TAG: ${{ steps.semantic.outputs.channel }}
          NPM_PACKAGE_VERSION: ${{ steps.semantic.outputs.next-version }}
      - name: Finish Release
        run: npx semantic-release
